// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/wuhuZhao/overpass_frontend_api/api/dao"
	"gorm.io/gorm"
)

type IdlHandler struct {
	dao *dao.IdlDao
}

func NewIdlHandler(db *gorm.DB) *IdlHandler {
	return &IdlHandler{dao: dao.NewIdlDao(db)}
}

// Create .
func (handler *IdlHandler) Create(ctx context.Context, c *app.RequestContext) {

}

// Update .
func (handler *IdlHandler) Update(ctx context.Context, c *app.RequestContext) {

}

// Delete .
func (handler *IdlHandler) Delete(ctx context.Context, c *app.RequestContext) {

}

// Find .
func (handler *IdlHandler) Find(ctx context.Context, c *app.RequestContext) {

}

// FindAll .
func (handler *IdlHandler) FindAll(ctx context.Context, c *app.RequestContext) {

}
